name: CI Checks

# Cada PR a develop o testing dispara lint/tests
on:
  pull_request:
    branches: [develop, testing]

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Commit Message Lint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs

      - name: ESLint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: TypeScript check
        run: npx tsc --noEmit
